### ISSUE TITLE
Wireless signal issues

### ISSUE THREAD

**Issue by rytido** [rytido/ncf-tech#4]
Signal issues from wireless transmitter are a regular occurrence.

**Comment by rytido** [comment]
Put the receiver in front of the drum set (because it was near the stage box and power source and not in the way). Didn't notice any signal issues. Need to come up with a more permanent location. Perhaps above the baptismal?

**Comment by kcarnold** [comment]
I still heard some hissing intermittently yesterday. It may have been when other people were also on stage (band, or the family for baptism), which might block direct line of sight.

I think it's a purely analog transmitter, so perhaps we could push the sensitivity on the transmitter a bit higher and bring down the audio gain on the receiver or board. That would boost the signal to noise over the RF channel. It may clip occasionally, but it would be analog clipping which isn't so bad.

**Comment by kcarnold** [comment]
The receiver by the piano seems to be doing great.
